# Moving Window - Focal Statistics

An example of moving window for raster data / numpy array. This approach takes the `SUM` of all unique values within the user defined window. This can be changed to the `SUM` of all values, or other metrics.

In [8]:
import pandas as pd
import numpy as np

In [9]:
# Create test data

# First create a sample raster data / numpy array
input_data = np.array([[0, 2, 3, 3, 0],
                       [1, 1, 1, 2, 1],
                       [5, 1, 1, 2, 0],
                       [1, 1, 0, 3, 1],
                       [10, 8, 1, 1, 1]])

# Create a weights matrix
weights = np.array([[0, 1, 0],
                    [1, 1, 1],
                    [0, 1, 0]])

In [10]:
# Define the custom function that applies sums the unique values where the weights == 1
def weighted_unique_sum(window, weights):
    # Apply the weights
    weighted_window = window[weights == 1]
    # Calculate the sum of unique values
    return np.sum(np.unique(weighted_window))

# Pad the input data to handle borders
pad_width = weights.shape[0] // 2
padded_data = np.pad(input_data, pad_width, mode='constant', constant_values=0)

# Initialize the result array
result = np.zeros_like(input_data)

# Iterate over the input data
for i in range(result.shape[0]):
    for j in range(result.shape[1]):
        # Extract the window around the current cell
        window = padded_data[i:i + weights.shape[0], j:j + weights.shape[1]]
        # Apply the custom function to the window
        result[i, j] = weighted_unique_sum(window, weights)

print("Input Data:")
print(input_data)
print("\nWeights Matrix:")
print(weights)
print("\nResulting Data after applying weighted unique sum:")
print(result)

Input Data:
[[ 0  2  3  3  0]
 [ 1  1  1  2  1]
 [ 5  1  1  2  0]
 [ 1  1  0  3  1]
 [10  8  1  1  1]]

Weights Matrix:
[[0 1 0]
 [1 1 1]
 [0 1 0]]

Resulting Data after applying weighted unique sum:
[[ 3  6  6  5  4]
 [ 6  3  6  6  3]
 [ 6  6  3  6  3]
 [16  9  4  6  4]
 [19 19  9  4  1]]
